const repositoryMock = {
  id: 380531627,
  node_id: "MDEwOlJlcG9zaXRvcnkzODA1MzE2Mjc=",
  name: "africafair",
  full_name: "josias/africafair",
  private: false,
  owner: {
    login: "josias",
    id: 104417,
    node_id: "MDQ6VXNlcjEwNDQxNw==",
    avatar_url: "https://avatars.githubusercontent.com/u/104417?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/josias",
    html_url: "https://github.com/josias",
    followers_url: "https://api.github.com/users/josias/followers",
    following_url: "https://api.github.com/users/josias/following{/other_user}",
    gists_url: "https://api.github.com/users/josias/gists{/gist_id}",
    starred_url: "https://api.github.com/users/josias/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/josias/subscriptions",
    organizations_url: "https://api.github.com/users/josias/orgs",
    repos_url: "https://api.github.com/users/josias/repos",
    events_url: "https://api.github.com/users/josias/events{/privacy}",
    received_events_url: "https://api.github.com/users/josias/received_events",
    type: "User",
    site_admin: false,
  },
  html_url: "https://github.com/josias/africafair",
  description: "Afric@Fair App repository",
  fork: false,
  url: "https://api.github.com/repos/josias/africafair",
  forks_url: "https://api.github.com/repos/josias/africafair/forks",
  keys_url: "https://api.github.com/repos/josias/africafair/keys{/key_id}",
  collaborators_url:
    "https://api.github.com/repos/josias/africafair/collaborators{/collaborator}",
  teams_url: "https://api.github.com/repos/josias/africafair/teams",
  hooks_url: "https://api.github.com/repos/josias/africafair/hooks",
  issue_events_url:
    "https://api.github.com/repos/josias/africafair/issues/events{/number}",
  events_url: "https://api.github.com/repos/josias/africafair/events",
  assignees_url:
    "https://api.github.com/repos/josias/africafair/assignees{/user}",
  branches_url:
    "https://api.github.com/repos/josias/africafair/branches{/branch}",
  tags_url: "https://api.github.com/repos/josias/africafair/tags",
  blobs_url: "https://api.github.com/repos/josias/africafair/git/blobs{/sha}",
  git_tags_url: "https://api.github.com/repos/josias/africafair/git/tags{/sha}",
  git_refs_url: "https://api.github.com/repos/josias/africafair/git/refs{/sha}",
  trees_url: "https://api.github.com/repos/josias/africafair/git/trees{/sha}",
  statuses_url: "https://api.github.com/repos/josias/africafair/statuses/{sha}",
  languages_url: "https://api.github.com/repos/josias/africafair/languages",
  stargazers_url: "https://api.github.com/repos/josias/africafair/stargazers",
  contributors_url:
    "https://api.github.com/repos/josias/africafair/contributors",
  subscribers_url: "https://api.github.com/repos/josias/africafair/subscribers",
  subscription_url:
    "https://api.github.com/repos/josias/africafair/subscription",
  commits_url: "https://api.github.com/repos/josias/africafair/commits{/sha}",
  git_commits_url:
    "https://api.github.com/repos/josias/africafair/git/commits{/sha}",
  comments_url:
    "https://api.github.com/repos/josias/africafair/comments{/number}",
  issue_comment_url:
    "https://api.github.com/repos/josias/africafair/issues/comments{/number}",
  contents_url:
    "https://api.github.com/repos/josias/africafair/contents/{+path}",
  compare_url:
    "https://api.github.com/repos/josias/africafair/compare/{base}...{head}",
  merges_url: "https://api.github.com/repos/josias/africafair/merges",
  archive_url:
    "https://api.github.com/repos/josias/africafair/{archive_format}{/ref}",
  downloads_url: "https://api.github.com/repos/josias/africafair/downloads",
  issues_url: "https://api.github.com/repos/josias/africafair/issues{/number}",
  pulls_url: "https://api.github.com/repos/josias/africafair/pulls{/number}",
  milestones_url:
    "https://api.github.com/repos/josias/africafair/milestones{/number}",
  notifications_url:
    "https://api.github.com/repos/josias/africafair/notifications{?since,all,participating}",
  labels_url: "https://api.github.com/repos/josias/africafair/labels{/name}",
  releases_url: "https://api.github.com/repos/josias/africafair/releases{/id}",
  deployments_url: "https://api.github.com/repos/josias/africafair/deployments",
  created_at: "2021-06-26T15:13:56Z",
  updated_at: "2022-03-09T12:14:06Z",
  pushed_at: "2022-04-04T03:52:26Z",
  git_url: "git://github.com/josias/africafair.git",
  ssh_url: "git@github.com:josias/africafair.git",
  clone_url: "https://github.com/josias/africafair.git",
  svn_url: "https://github.com/josias/africafair",
  homepage: null,
  size: 4685,
  stargazers_count: 0,
  watchers_count: 0,
  language: "CSS",
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  has_discussions: false,
  forks_count: 0,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 0,
  license: null,
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: [],
  visibility: "public",
  forks: 0,
  open_issues: 0,
  watchers: 0,
  default_branch: "master",
};

export default repositoryMock;
