const userMock = {
  login: "josias",
  id: 104417,
  node_id: "MDQ6VXNlcjEwNDQxNw==",
  avatar_url: "https://avatars.githubusercontent.com/u/104417?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/josias",
  html_url: "https://github.com/josias",
  followers_url: "https://api.github.com/users/josias/followers",
  following_url: "https://api.github.com/users/josias/following{/other_user}",
  gists_url: "https://api.github.com/users/josias/gists{/gist_id}",
  starred_url: "https://api.github.com/users/josias/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/josias/subscriptions",
  organizations_url: "https://api.github.com/users/josias/orgs",
  repos_url: "https://api.github.com/users/josias/repos",
  events_url: "https://api.github.com/users/josias/events{/privacy}",
  received_events_url: "https://api.github.com/users/josias/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 5,
  public_gists: 0,
  followers: 1,
  following: 0,
  created_at: "2009-07-13T13:29:44Z",
  updated_at: "2022-08-16T01:57:50Z",
};

export default userMock;
